### ISSUE TITLE
Checklist Low Hanging Fruit

### ISSUE THREAD

**Issue by devsjors** [TomasS666/frontend-data#7]
### Low Hanging Fruit
**Readme**
- [x] Gitignore
- [x]  link to live demo on github pages
- [x]  description
		- Deze zou ik op de plek zetten waar je ook de livelink neerzet en niet in je readme
- [x]  concept 
		- Misschien wat meer uitleggen over hoe de interactie werkt die de gebruiker kan hebben
- [x] image
- [x] link to example used to build visualization (screenshots)
		- Duidelijk aangeven welke link is van het voorbeeld die je hebt gebruikt
- [x] data used (what's done with invalid and empty values?)
		- Duidelijk aangegeven welke data je gebruikt. Misschien terug laten komen door middel van een screenshot waarin je de data ziet in je visualisatie?
- [x] plagiarism and acknowledgements

**Wiki**
- [ ] wiki
- [ ]  Is the update pattern (data flow) documented?
- [ ] (link to) functional pattern

**Concept**
- [x]  Does the visualization makes sense on it's own? (labels, axis, titles)
		- Duidelijk visualisatie en je ziet meteen wat je over probeert te brengen
- [x] What patterns do you see in this visualization. What can a user (viewer) learn?
		- Soorten wapens verdeeld over de hele wereld. 
		- Misschien meer inzoomen op de kaart door hem minder hoog te maken dat je gelijk wat meer ingezoomd bent.
- [x] Is the visualization build for a target audience? (write in issue)
		- De doelgroep is niet bepaald dus ik weet niet of de visualisatie voor een bepaalde doelgroep is.
- [x] Data veranderd nog niet. Wel een heel vet dat je op een bol kan klikken en dan meer details ziet. Ik verwacht te kunnen filteren tussen de verschillende soorten wapens

**Code**
Code ziet er goed uit en is ook goed te volgen. Fijn dat je het hebt opgebroken in modules.
